apiVersion: v1
kind: Namespace
metadata:
  name: feroze-test
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  namespace: feroze-test
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  namespace: feroze-test
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
---
apiVersion: iam.services.k8s.aws/v1alpha1
kind: Policy
metadata:
  annotations:
    services.k8s.aws/deletion-policy: retain
  name: steftest
  namespace: 026281491146-access
spec:
  description: Managed by stefan
  name: steftest
  path: /
  policyDocument: '{"Statement":[{"Action":["autoscaling:TerminateInstanceInAutoScalingGroup","ec2:DescribeImages","ec2:GetInstanceTypesFromInstanceRequirements","eks:DescribeNodegroup","autoscaling:DescribeAutoScalingGroups","autoscaling:DescribeAutoScalingInstances","autoscaling:DescribeLaunchConfigurations","autoscaling:DescribeScalingActivities","autoscaling:DescribeTags","ec2:DescribeInstanceTypes","ec2:DescribeLaunchTemplateVersions"],"Effect":"Allow","Resource":["*"],"Sid":"ManageClusterAutoscaling"}],"Version":"2012-10-17"}'
  tags:
  - key: porter.run/managed
    value: "true"
  
